version: '3.7'

services:
    db:
        image: mysql:8.0.17
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_RANDOM_ROOT_PASSWORD=yes
    web:
        build: .docker/php
        depends_on:
            - db
        volumes:
            - .:/var/www/project:cached
        ports:
            - 8010:80
    node:
        image: node:12-alpine
        command: sh -c "yarn install && yarn encore dev --watch"
        volumes:
            - .:/app:cached
        working_dir: /app

    composer:
        image: composer:1.9.0
        command: install
        depends_on:
            - web
        volumes:
            - .:/app

    pma:
        image: phpmyadmin/phpmyadmin
        container_name: pma_project
        environment:
            - PMA_HOST=db
        ports:
            - 8080:80
        depends_on:
            - db
