<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7omtxcO\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7omtxcO/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container7omtxcO.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container7omtxcO\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container7omtxcO\App_KernelDevDebugContainer([
    'container.build_hash' => '7omtxcO',
    'container.build_id' => 'c6b4ade5',
    'container.build_time' => 1594974681,
], __DIR__.\DIRECTORY_SEPARATOR.'Container7omtxcO');
